### PR TITLE
Improved unsupported distro error and added support for Manjaro Linux

### PR DESCRIPTION
**Pull request by joaompinto**

### CODE REVIEW

**Comment by ianmiell** [comment]
Thanks so much for the PR!
I will release this weekend sometime.
Do you have a use case for ShutIt I can help with?

**Comment by joaompinto** [comment]
@ianmiell Thanks for the quick feedback :)

I am researching tools for a potential Kubernetes customized PaaS build tool, I still need to check https://github.com/ianmiell/shutit-kubernetes :)

**Comment by ianmiell** [comment]
Actually I'm working on a Vagrant-based version of just that - but the
source won't be on github... tweet me your email @ianmiell or get in touch
if you want to know more.

**Comment by ianmiell** [comment]
And you might be more interested in this, which is my test framework for
Chef-deploymed OpenShift clusters:

https://github.com/ianmiell/shutit-openshift-cluster

**Pull request merged**
