### PR TITLE
Actually allow ctrl-c to quit, ctrl-z is annoying

### PR DESCRIPTION
**Pull request by aidanhs**
I don't even know why this interception is happening since it apparently never works...

`if False and 'shutit' in frame.f_locals:`

### CODE REVIEW

**Comment by ianmiell** [comment]
Hmmmm, Hazleton and I were huge fans of this as it stopped us accidentally killing builds. Which happened a lot.

**Comment by aidanhs** [comment]
Well, it still stops you accidentally killing builds. It just allows you to quit if you double ctrl-c.

**Comment by aidanhs** [comment]
I can change the message if that's the intention.

**Comment by ianmiell** [comment]
Oh, very good.

**Pull request merged**
